### PR TITLE
[485316]: HW1 (step 2)

### PR DESCRIPTION
**Pull request by jurf**
Building off #29 and superseding #30.

### CODE REVIEW

**Comment by jurf** [comment]
Done

**Comment by jurf** [comment]
1fb7c026f35f842e25f57e5e2a993806d6f27a47 Implement TODOs, increase test coverage
a7abd75270b69eac3b21d9cb9bc37544f7d67e9b Document functionality in README
2f01d7a8390837c7e87619ce24b72506b1d9843f Reformat
0af5072df269994cb764db3a8e29c8d44f0d7edd Implement missing functionality, tests
c0d5feae0d238718edc60974e8f3d3265c7b07de Enable flake8 in VS Code
2ea3d79139abc0cbfdb75fbef2ef546d969db1b7 Add Travis badge
c8558bbf358d723cb01c076019cbfe08c60b773f Upgrade Travis build to Ubuntu 18.04
9dfbfb79969dc1b96c5ed7d8b547b6c2671c0ab2 Add VS Code configuration
807db54887ba3e6eafe8d44f8f24bffa935d7ece Fix tests
2e6e4ffd27b0e3f57777d25998b8d15bdd409e7f Fix launching module

**Review by ph4r05 — CHANGES_REQUESTED** [review]
Code is nice, but commits have to be signed

**Comment by jurf** [comment]
Fixed.

**Review by ph4r05 — APPROVED** [review]

**Pull request closed without merging**
