### PR TITLE
[485115]: PR2 Vector and Matrix

### PR DESCRIPTION
**Pull request by TomasZilinek**
in step2

### CODE REVIEW

**Comment by TomasZilinek** [comment]
Done

**Comment by TomasZilinek** [comment]
437acf4c81bc5dd887155a485beac5d6ccc9ebfc
846902e622b44d5b3d6d64f23d19fe8b78e49b51
f849b6f46783230ad09b97b81360288691c41a66
acbda8cd56b4aaccd55e945d9f5af19b6bd41819
6e9b10d2b4e9d4ae99de6929f7350b39c76548cf
11af32ee89f3f5fb2a74f1bb299e610569f53427 - import the code (but sqashed)
e165cfdc9e435fdf5a96dde79d066ba00abb2035 - fix unit tests
54a3928ba054f1b97e496d1fe29064d85b5c6c93 - the squashed commit

**Comment by ph4r05** [comment]
@TomasZilinek Travis fails, pls make sure it passes and executes some tests really. I cannot accept it like this. Thanks!

**Comment by ph4r05** [comment]
Pls read the assignment again and make sure the submission follows the requirements.

- there should be only 1 commit, squashed, signed.

**Comment by TomasZilinek** [comment]
> @TomasZilinek Travis fails, pls make sure it passes and executes some tests really. I cannot accept it like this. Thanks!

Sorry I am writing so late, my mail was not forwarded to my active mail address. I cannot figure out why it is giving me the error: "ModuleNotFoundError: No module named 'ossdev'". Is it done for purpose? It was driving me crazy and I was right before the deadline so I just commited the "not passing version". I will try to correct it but that means doing the whole part 2 again.

**Comment by TomasZilinek** [comment]
> @TomasZilinek Travis fails, pls make sure it passes and executes some tests really. I cannot accept it like this. Thanks!

Sorry I am writing so late, my mail was not forwarded to my active mail address. I cannot figure out why it is giving me the error: "ModuleNotFoundError: No module named 'ossdev'". Is it done for purpose? It was driving me crazy and I was right before the deadline so I just commited the "not passing version". I will try to correct it but that means doing the whole part 2 again.

**Review by ph4r05 — DISMISSED** [review]
Your first PR is not great. The title is missing, there are some conflicts, Travis was not configured.
This PR has Travis working but the test matrix is changed, only one python version is tested (not recommended approach).

**Review by ph4r05 — CHANGES_REQUESTED** [review]
Commits are not signed (merged are OK), pls fix it. And also fix the Travis so all previously tested python versions are tested.

**Comment by ph4r05** [comment]
@TomasZilinek pls squash and sign the last commit. Then I can award you HW points. Tag me to the comment once you are done pls.
Thx.

**Comment by TomasZilinek** [comment]
Done @ph4r05

**Review by ph4r05 — APPROVED** [review]

**Comment by ph4r05** [comment]
This now looks good, thanks!

**Pull request closed without merging**
