### PR TITLE
[485607]: HW02 step1

### PR DESCRIPTION
**Pull request by mksoska**

### CODE REVIEW

**Comment by mksoska** [comment]
It's done.

**Comment by ph4r05** [comment]
your commits are not signed, pls squash and sign

**Review by ph4r05 — CHANGES_REQUESTED** [review]
Signed commits needed

**Comment by mksoska** [comment]
Forcepushed the same, but signed commit.

**Review by ph4r05 — DISMISSED** [review]

**Review by ph4r05 — APPROVED** [review]

**Comment by ph4r05** [comment]
Approved, HW done, closing

**Pull request closed without merging**
