### PR TITLE
[485638]: Vector and metrix Impl

### PR DESCRIPTION
**Pull request by tomas-janicek**

### CODE REVIEW

**Comment by tomas-janicek** [comment]
Done

**Comment by tomas-janicek** [comment]
6f9d4526d2aba73fe8f1be8aed84f5c6e3e8b1f6 - Add vector impl
0197ca0598da579aadeeeefbcee6440332ab6260 - Add vector tests
de2b7f608e090e4c6edefc2efb75e6c9f589d7bc - Fix Travis Build
880cae79f76904be288fd121fdb99e1f95d09405 - Update Readme and Add travis badge
e15f00681a1dd84d0292e9981b86caeb8d73287d - Add sub comment
70d47009b052bbe4d10814385377cd1c8ad4c342 - Finished Impl
6949019a8c4851e448d99f6b67c6d35b8b0920ac - Finished Impl
e775a3df5fa23b05dcee0b007f32e559dbcc88ff - Update vector
49e71f29b5322abb27be07d349fb86729b414a91 - Update vector tests
09b09e82a1380fa3aba1ff0e72dc13c739eda162 - Fix Travis build
0450cf9d76b752e055d8b6c5ebd8ec965714eb8d - Finished Impl

**Comment by ph4r05** [comment]
Hi @TomasJani, pls check your Travis, it is passing but with 0 tests being executed.

**Comment by tomas-janicek** [comment]
> Hi @TomasJani, pls check your Travis, it is passing but with 0 tests being executed.

It should be fine now.

**Review by ph4r05 — APPROVED** [review]
👍

**Pull request closed without merging**
