### PR TITLE
[485535] : HW02-1

### PR DESCRIPTION
**Pull request by Ydeu**

### CODE REVIEW

**Comment by Ydeu** [comment]
Done.

**Comment by ph4r05** [comment]
Can you pls identify yourself? 😅

**Comment by Ydeu** [comment]
Oh, Daniel Lacko (485535) here. Martin Ukrop knows about this GitHub
account (Ydeu), so I assumed you also knew about it.

ut 28. 1. 2020 o 12:42 Dušan Klinec <notifications@github.com> napísal(a):

**Comment by ph4r05** [comment]
Yep the UCO was correctly present in the title, so I removed the comment :)

**Review by ph4r05 — APPROVED** [review]

**Comment by ph4r05** [comment]
Approved, HW done, closing

**Pull request closed without merging**
