### PR TITLE
[487603]: Assignment 2 - step 2

### PR DESCRIPTION
**Pull request by nitrajka**

### CODE REVIEW

**Comment by nitrajka** [comment]
Done.

**Comment by ph4r05** [comment]
One additional thing: pls add commit info file from the assignment here, as a comment (plaintext, no attachments). (and check the signed commit requirement)

**Comment by ph4r05** [comment]
Squash all to one commit pls, signed. Thanks!

**Comment by nitrajka** [comment]
ossdev-hw-02-487603.txt
--------------STEP1--------------
f326c6269128b7287a11104778270a902a2be804 - implement TODO functions in Vector class
f8ae08be37491d979cf3ca7fb248ca6c27c30f9d - write tests for implemented functions
e33afb79bfcff24c2a0556e2167aeaa36a02a5d4 - add test for reverse
a2bb19a80c9f9ca9067260babf8f7482dd1879ec - change distribution version in travis yaml file
0895f12712790b5c4c3ec93fc5885bbc7e2b45c7 - document implemented operations on vectors
f7c42ca7f27de1a17de8fa375d9119e40da6d628 - add requested comment to __sub__

-------after squash
4f78e13577a4c26a7987ba2b426b475de8be99ce - implement TODO functions, tests, __sub__ comment


--------------STEP2--------------
10ace9ea18862b677ab24bde151e7c8293d1b7e8 - pull master from new origin
84cda903c405e5f2e575d57f380e0aabfd239db7 - implement TODO functions, tests, __sub__ comment
2504575c110dc892afb1fd034e3b45090bd76d90 - implement todo functions
7a80cef8f3da7968d2c88320065d0a2087cb9671 - test dot() from Vector class
7b772a5da62897ce770283deb1d02bcca4c8546b - rename test file

------after squash
2be21ec2f3448a6834fca6f6bd1bd3fb0b5c529c - implement TODO functions, tests, __sub__ comment, test dot(), rename test file


---------
the last one should be signed.

**Comment by ph4r05** [comment]
Just curiosity: I've just noticed the change of `'` to `"`, did you use some formatter like `black` or it was done by IDE or manually?

Another one: did you have to resolve conflicts on your own (no auto-merge, I mean ... `<<<<HEAD`) after pulling from repo 2?

btw - thanks, looks good 👍

**Review by ph4r05 — DISMISSED** [review]

**Comment by nitrajka** [comment]
Yes, I used black 😄I set it up for my ide (Pycharm) to trigger on save. I always do it on every python project manually, if there isn't another linter required. I hope it is not a problem. (I also always create a virtualenv.)

Yes, I had to resolve them manually. I did so in Pycharm. 

Thank you 😸

**Comment by ph4r05** [comment]
Btw I just noticed the tests are not quite fixed.
https://travis-ci.com/crocs-muni/open-source-development-course-hw02-1/jobs/280917806

0 tests was run. There is a little catch. Could you pls check the PR fixing the tests from the assignment and fix it? Should be fast. Thanks! :)

**Review by ph4r05 — CHANGES_REQUESTED** [review]
0 tests run in Travis.

**Comment by ph4r05** [comment]
just a note - Fix should go as fixup, i.e., fix it, squash-sign and force push pls.

**Comment by ph4r05** [comment]
just ping me with a mention when this is done. thanks!

**Comment by ph4r05** [comment]
> Yes, I used black 😄I set it up for my ide (Pycharm) to trigger on save. I always do it on every python project manually, if there isn't another linter required. I hope it is not a problem. (I also always create a virtualenv.)

Thats a good approach. There is no problem if yo know what are you doing. 
I created the repo in a way it uses non-pep8 quotes (AFAIK), for this purpose - demonstrate that linting / reformatting the codebase is not usually appropriate when submitting PR as they bring additional complexity and non-semantic changes. This makes review significantly harder and people hate it, usually. Reformatting changes should be discussed with maintainers and go as a separate PR.

**Comment by nitrajka** [comment]
@ph4r05 
That is weird, that the tests do not run. Locally they are passing. All of them. In branch `pr/step2`.
Screen Shot 2020-01-28 at 17 46 17

EDIT: Do you know, what should I do? Because I do not.

**Comment by ph4r05** [comment]
Yes I do, but I want you to figure it out :)
It works for you because you run the tests from IDE, it seems.

Hints:
- check what `.travis.yml` does precisely, execute same commands. Are tests executed?
- inspect PR fixing the problem: https://github.com/crocs-muni/open-source-development-course-hw02-2/pull/1

**Comment by nitrajka** [comment]
@ph4r05 
This guy at the bottom ( https://stackoverflow.com/questions/5088960/python-m-unittest-discover-does-not-discover-tests ) suggested adding an empty `__init__.py` file to a test folder. I did so and the command from `test-travis.sh` ran 9 tests instead of 0. Hope it will work on travis as well.

Now I have to edit the comment with commit hashes.

**Comment by ph4r05** [comment]
good job!

**Review by ph4r05 — APPROVED** [review]

**Comment by ph4r05** [comment]
Approved, HW done, closing

**Pull request closed without merging**
