### PR TITLE
[420803]: pr2

### PR DESCRIPTION
**Pull request by JayDee81**
pr2

### CODE REVIEW

**Comment by JayDee81** [comment]
Done

**Comment by ph4r05** [comment]
One additional thing: pls add commit info file from the assignment here, as a comment (plaintext, no attachments)

**Comment by ph4r05** [comment]
Commit 03fedc6c833e0a249b0028a91f4ce567ce20332c message is not really helping (you don't have to change the history now)

**Comment by JayDee81** [comment]
f51d07495fd413f4fb638cc826aee142b75bd6fe - implementation
68bfb69a8bbb8dfd6a47e8eff1e08be0e1f83c3d - tests
e0ee2ae3c57ddb2665d6e712e34aaac6b91f7bce - build badge and change python dist to xenial
f645bb891470a25f961f621c48cf78358b9bcb77 - update readme
04b21d50a24c43cfb70060e4ffc0bb36d093ff38 - comment __sub__
b801d46b80af153f00e43b1d86b8f510f6bba5ad - squashed commits
cb6f37a21d10b87464d47cf5ba15358a4fd094bb - rebase
2f1a01b6fa45d433e7ee6cb3363428cb0a7fef5a - implementation p2
2c276e4bc3869605f5fcd4f4723a29da4e7004c3 - tests
fdfb96ff7682c723bf3be5b605ca645afd2f1bcc - bionic dist
55cd9ef20e3e87cc459a6b0da366aecfb16ad1b5 - implement todos, add tests, fix Travis tests (squashed)

**Comment by ph4r05** [comment]
Next time work more on the PR desc and commit messages

**Review by ph4r05 — DISMISSED** [review]

**Review by ph4r05 — CHANGES_REQUESTED** [review]
Travis shows tests are passing, but 0 of them is run. 
PR from the assignment fixes this issue, pls fix it also here (minor catch). Thanks!

**Comment by ph4r05** [comment]
just a note - Fix should go as fixup, i.e., fix it, squash-sign and force push pls.

**Comment by ph4r05** [comment]
just ping me with a mention when this is done. thanks!

**Comment by JayDee81** [comment]
@ph4r05 I don't understand. Do you mean the PR that changes python distribution for Travis testing from trusty to bionic? Because that one is already included here.

**Comment by ph4r05** [comment]
Hints:

- check what .travis.yml does precisely, execute same commands. Are tests executed?
- inspect PR fixing the problem: crocs-muni/open-source-development-course-hw02-2#1

**Comment by JayDee81** [comment]
@ph4r05 Done. Edited comment with commit hashes.

**Review by ph4r05 — APPROVED** [review]

**Comment by ph4r05** [comment]
Approved, HW done, closing

**Pull request closed without merging**
