### PR TITLE
[485638]: Vector Functionality Implementation

### PR DESCRIPTION
**Pull request by tomas-janicek**

### CODE REVIEW

**Comment by tomas-janicek** [comment]
Sub comment added and commits were squashed.

**Comment by ph4r05** [comment]
Hi @TomasJani, pls check your Travis, it is passing but with 0 tests being executed.

**Comment by tomas-janicek** [comment]
> Hi @TomasJani, pls check your Travis, it is passing but with 0 tests being executed.

It should be fine now.

**Review by ph4r05 — APPROVED** [review]
👍

**Pull request closed without merging**
