### PR TITLE
[485115]: PR step 1

### PR DESCRIPTION
**Pull request by TomasZilinek**
according to step: Create a PR with your changes against the forked repo, PR name has to start with [WIP] [UCO]: with your UCO.

### CODE REVIEW

**Comment by TomasZilinek** [comment]
Add a simple python comment to the __sub__ and to squash all the commits then.

**Comment by TomasZilinek** [comment]
commenting according to: Notify reviewer it's done with a PR comment, remove [WIP] from the PR title as your PR is approved now.

It's done!!!

**Comment by ph4r05** [comment]
The PR name is not great :)

**Review by ph4r05 — CHANGES_REQUESTED** [review]
Formally I am going to reject this as no Travis is configured.

**Comment by ph4r05** [comment]
Man, this PR is a mess, sorry. Travis still not running, many testing commits without squash, ...reject...

**Comment by ph4r05** [comment]
But part2 is OK so we can close this. No need to fix it.

**Pull request closed without merging**
